#!/usr/bin/env python3
DEPS_WITH_RUST = {
	"maturin": "maturin",
	"cryptography": "cryptography",
}

import json
import pathlib
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.request
import zipfile

__dirpath__ = pathlib.Path(__file__).parent

# Source: https://github.com/pypa/packaging/blob/21.3/packaging/version.py#L225-L254
VERSION_PATTERN = r"""
    v?
    (?:
        (?:(?P<epoch>[0-9]+)!)?                           # epoch
        (?P<release>[0-9]+(?:\.[0-9]+)*)                  # release segment
        (?P<pre>                                          # pre-release
            [-_\.]?
            (?P<pre_l>(a|b|c|rc|alpha|beta|pre|preview))
            [-_\.]?
            (?P<pre_n>[0-9]+)?
        )?
        (?P<post>                                         # post release
            (?:-(?P<post_n1>[0-9]+))
            |
            (?:
                [-_\.]?
                (?P<post_l>post|rev|r)
                [-_\.]?
                (?P<post_n2>[0-9]+)?
            )
        )?
        (?P<dev>                                          # dev release
            [-_\.]?
            (?P<dev_l>dev)
            [-_\.]?
            (?P<dev_n>[0-9]+)?
        )?
    )
    (?:\+(?P<local>[a-z0-9]+(?:[-_\.][a-z0-9]+)*))?       # local version
"""

if len(sys.argv) < 2:
	print("Usage: ./pypi-dependencies-fixup-rust.py [Path_to_flatpak-cargo-generator]", file=sys.stderr)
	sys.exit(1)
cargo_generator = sys.argv[1]

# Ensure output directory exists
out_dir = __dirpath__ / "cargo-dependencies"
out_dir.mkdir(parents=True, exist_ok=True)

# Load python dependency list generated by `flatpak-pip-generator`
with open(__dirpath__ / "pypi-dependencies.json", "r") as f:
	module = json.load(f)

# For packages with Rust dependencies, generate Cargo configuration and update
# build-options accordingly
#
# This step is written to be idempotent, so that subsequent invocations do not
# result in breaking an otherwise working file.
for submodule in module["modules"]:
	# Skip submodule file references
	if not isinstance(submodule, dict):
		continue

	# Check if submodule is known to have Rust
	name = submodule["name"].removeprefix("python3-")
	if name not in DEPS_WITH_RUST:
		continue
	rust_dep_name = DEPS_WITH_RUST[name]

	# Create regexp to match dependency from file name
	rust_dep_regexp = re.compile(
		r"/(?P<filename>(?P<basename>" + re.escape(rust_dep_name) + r"-" + VERSION_PATTERN + r")\.(?P<ext>tar\.(?:gz|bz2|xz)|whl))$",
		re.VERBOSE
	)

	with tempfile.NamedTemporaryFile() as cargo_lock:
		# Iterate over sources to find Rust dependency
		for source in submodule["sources"]:
			if not isinstance(source, dict) or source.get("type") != "file":
				continue

			# Look for file with expected URL
			match = rust_dep_regexp.search(source["url"])
			if match is None:
				continue

			with urllib.request.urlopen(source["url"]) as dl:
				assert match.group("ext").startswith("tar."), "Rust package must be source distribution"

				with tarfile.open(match.group("filename"), "r|*", dl) as dl:
					while (item := dl.next()) is not None:
						if item.name != f"{match.group('basename')}/Cargo.lock":
							continue

						with dl.extractfile(item) as src:
							shutil.copyfileobj(src, cargo_lock.file)
							cargo_lock.file.close()
						break
					else:
						print(f"Failed to find “Cargo.lock” inside “{source['url']}”", file=sys.stderr)
						sys.exit(1)
			break
		else:
			print(f"Failed to find source “{rust_dep_name}” for submodule “{name}”", file=sys.stderr)
			sys.exit(1)

		# Call `flatpak-cargo-generator` to convert `Cargo.lock` to sources list
		subprocess.run(
			[cargo_generator, "-o", out_dir / f"{rust_dep_name}.json", cargo_lock.name],
			check = True
		)

	submodule["build-options"] = {
		"append-path": "/usr/lib/sdk/rust-stable/bin",
		"env": {
			"CARGO_HOME": f"/run/build/python3-{name}/cargo",
			"CARGO_NET_OFFLINE": "true",
			"RUST_BACKTRACE": "1",
		}
	}

	if f"cargo-dependencies/{rust_dep_name}.json" not in submodule["sources"]:
		submodule["sources"].append(f"cargo-dependencies/{rust_dep_name}.json")

# Write back updated file contents
with open(__dirpath__ / "pypi-dependencies.json", "w") as f:
	module = json.dump(module, f, ensure_ascii=False, indent="\t")